package view;

import java.text.DecimalFormat;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.TimeUnit;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.applet.Applet;
import java.applet.AudioClip;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import static view.CanvasTelaInicial.getHoras;

public class TelaInicial extends javax.swing.JFrame {
    public static int tlivre;
    int millis;
    int delay = 1000;   // tempo de espera antes da 1ª execução da tarefa.
    int interval = 1000;  // intervalo no qual a tarefa será executada.
    int horas = Integer.parseInt(getHoras()); //retorna a hora atual.
    
    Timer timer = new Timer();
    DecimalFormat doisDigitos = new DecimalFormat("00");
    Image icone = new ImageIcon(getClass().getResource("/assets/icone.png")).getImage();
    URL url = getClass().getResource("/assets/som.wav");      

    public static int getTlivre() {
        return tlivre;
    }

    public void setTlivre(int tlivre) {
        this.tlivre = tlivre;
    }
    
    
    
    private void tocarSom(){
        AudioClip som;  	                
        try {           
            som = Applet.newAudioClip(url);
            som.stop();
            som.play();          
        } catch (Exception erro) {
            System.out.println("Erro!");
        }                   
    }
    
    public TelaInicial() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("DungeonLoop");
        setIconImage(icone);
        setResizable(false);
        
        if(horas <= 13){
            lblUtil.setForeground(new Color(100,100,255));
            lblPausa.setForeground(new Color(100,100,255));
        }else if(horas >= 13 && horas < 18){
            lblTempo.setForeground(new Color(255,255,153));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new CanvasTelaInicial();
        boxUtil = new javax.swing.JComboBox<>();
        lblTempo = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        barraProg = new javax.swing.JProgressBar();
        btnTestar = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        boxPausa = new javax.swing.JComboBox<>();
        lblUtil = new javax.swing.JLabel();
        lblPausa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 149));
        setMinimumSize(new java.awt.Dimension(400, 149));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        boxUtil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "25 min.", "20 min.", "15 min.", "10 min.", "5 min." }));

        lblTempo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTempo.setForeground(new java.awt.Color(204, 0, 0));
        lblTempo.setText("00:00:00");

        btnIniciar.setBackground(new java.awt.Color(102, 102, 102));
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar Pomodoro!");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        barraProg.setMaximum(1500000);

        btnTestar.setBackground(new java.awt.Color(0, 153, 102));
        btnTestar.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnTestar.setText("Sobre");
        btnTestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestarActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(102, 102, 102));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Resetar");
        btnReset.setEnabled(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        boxPausa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "25 min.", "20 min.", "15 min.", "10 min.", "5 min." }));
        boxPausa.setSelectedIndex(4);

        lblUtil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUtil.setForeground(new java.awt.Color(102, 255, 204));
        lblUtil.setText("Tempo útil:");
        lblUtil.setToolTipText("Quanto tempo irá passar em cada intervalo de atividade.");

        lblPausa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPausa.setForeground(new java.awt.Color(102, 255, 204));
        lblPausa.setText("Tempo de pausa:");
        lblPausa.setToolTipText("Quanto tempo irá passar em cada intervalo livre.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTestar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIniciar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblUtil)
                                .addGap(18, 18, 18)
                                .addComponent(boxUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblPausa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxPausa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(barraProg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lblTempo))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraProg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxPausa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUtil)
                    .addComponent(lblPausa))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnIniciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTestar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 416, 239);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        btnReset.setEnabled(true);
        
        if(boxPausa.getSelectedIndex() == 0){
            tlivre = 25;
            System.out.println("25 min de pausa");
        }else if(boxPausa.getSelectedIndex() == 1){
            tlivre = 20;
            System.out.println("20 min de pausa");
        }else if(boxPausa.getSelectedIndex() == 2){
            tlivre = 15;
            System.out.println("15 min de pausa");
        }else if(boxPausa.getSelectedIndex() == 3){
            tlivre = 10;
            System.out.println("10 min de pausa");
        }else if(boxPausa.getSelectedIndex() == 4){
            tlivre = 5;
            System.out.println("5 min de pausa");
        }        
        
        if(boxUtil.getSelectedItem().toString().equals("25 min.")){
            millis = 1500000;;
            barraProg.setMaximum(1500000);
        }else if(boxUtil.getSelectedItem().toString().equals("20 min.")){
            millis = 1200000;
            barraProg.setMaximum(1200000);
        }else if(boxUtil.getSelectedItem().toString().equals("15 min.")){
            millis = 900000;
            barraProg.setMaximum(900000);
        }else if(boxUtil.getSelectedItem().toString().equals("10 min.")){
            millis = 600000;
            barraProg.setMaximum(600000);
        }else if(boxUtil.getSelectedItem().toString().equals("5 min.")){
            millis = 300000;
            barraProg.setMaximum(300000);
        }
        
        lblTempo.setForeground(new Color(60, 222, 184));
        btnIniciar.setEnabled(false);
        timer.schedule(new TimerTask() {
        @Override
        public void run() {
            barraProg.setValue(barraProg.getValue() + 1000);
            System.out.println(barraProg.getValue());
            millis = millis - 1000;  
            
            if(millis == 0){
                timer.cancel();
                new Taverna().setVisible(true);
                tocarSom();
                dispose();
            }
            
            //mexendo no label txtTempo
            lblTempo.setText(String.format("%02d:%02d:%02d", 
                TimeUnit.MILLISECONDS.toHours(millis),
                TimeUnit.MILLISECONDS.toMinutes(millis) - 
                TimeUnit.HOURS.toMinutes(TimeUnit.MILLISECONDS.toHours(millis)),
                TimeUnit.MILLISECONDS.toSeconds(millis) - 
                TimeUnit.MINUTES.toSeconds(TimeUnit.MILLISECONDS.toMinutes(millis))));            
        }
        }, 0, interval);    
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnTestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestarActionPerformed
        // TODO add your handling code here:
        Icon icon = new ImageIcon(getClass().getResource("/assets/icone.png")); 
        //JOptionPane.showConfirmDialog(null, "Criado por Íkaro Nascimento", "teste", WIDTH, WIDTH, icon);
        JOptionPane.showMessageDialog(this, "Criado por Íkaro Nascimento em 2019", "Sobre o Programa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTestarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        timer.cancel();
        dispose();
        new TelaInicial().setVisible(true);      
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProg;
    private javax.swing.JComboBox<String> boxPausa;
    private javax.swing.JComboBox<String> boxUtil;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTestar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPausa;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JLabel lblUtil;
    // End of variables declaration//GEN-END:variables
}
